version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_DB_URL=${AWS_DB_URL}
      - AWS_DB_USERNAME=${AWS_DB_USERNAME}
      - AWS_DB_PASSWORD=${AWS_DB_PASSWORD}