services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/uploads:/app/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}