name: CI/CD Deploy to AWS EC2

on:
  push:
    branches: [ "dev2" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_DB_URL: ${{ secrets.AWS_DB_URL }}
          AWS_DB_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
          AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          envs: AWS_DB_URL,AWS_DB_USERNAME,AWS_DB_PASSWORD
          script: |
            cd ~/black_sea_walnut
            git fetch origin
            git checkout dev2
            git pull origin dev2

            docker compose down
            docker compose up -d --build

            docker image prune -f