name: CI/CD Deploy to AWS EC2

on:
  push:
    branches: [ "dev2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AWS_DB_URL}}
          username: ${{secrets.AWS_DB_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          script: |
            cd ~/black_sea_walnut
            git pull origin dev2
            docker compose up -d --build